apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-runasnonroot
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces:
                - security-tools
                - kube-system
      validate:
        message: "Containers must not run as root. Set runAsNonRoot: true."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
